FROM python:3.8.5-slim

WORKDIR /app/dts-auto-brief-v1

ADD ./dts-auto-brief-v1.tar /app/

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN pip3 install /app/dts-auto-brief-v1/docker/boost-py-0.1.0.tar.gz && pip3 install -r /app/dts-auto-brief-v1/requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com

EXPOSE 8999


#CMD ["/bin/bash", "/app/dts-email-alarm-system/docker/start.sh"]
